from __future__ import annotations

import argparse
import json
import os
import time

from collections import Counter
from dataclasses import dataclass
from typing import Any

from confluent_kafka import KafkaException, Producer
from dotenv import load_dotenv

from src.producer.transaction_generator import (
    GeneratedTransaction,
    TransactionGenerator,
)


load_dotenv()


# ============================================================
# PRODUCER METRICS
# ============================================================

@dataclass
class ProducerMetrics:
    """
    Lightweight producer-side operational statistics.

    These metrics are only for simulator observability.
    The ground-truth fraud label is NOT sent in the Kafka payload.
    """

    generated: int = 0
    delivery_successes: int = 0
    delivery_failures: int = 0

    simulated_fraud: int = 0
    duplicates: int = 0
    late_within_watermark: int = 0
    late_beyond_watermark: int = 0


# ============================================================
# KAFKA PRODUCER
# ============================================================

class FraudKafkaProducer:
    """
    High-throughput Kafka producer for synthetic financial events.

    Important architectural choice:
        Kafka key = user_id

    Using user_id as the key causes transactions for the same user
    to be consistently routed to the same Kafka partition.

    This reduces unnecessary repartitioning pressure and aligns
    naturally with the downstream stateful fraud-processing key.
    """

    def __init__(
        self,
        *,
        bootstrap_servers: str,
        topic: str,
    ) -> None:

        self.topic = topic

        self.metrics = ProducerMetrics()

        self.fraud_type_counts: Counter[str] = Counter()

        self.producer = Producer(
            {
                # ------------------------------------------------
                # CONNECTION
                # ------------------------------------------------

                "bootstrap.servers": bootstrap_servers,

                "client.id": "fraud-transaction-simulator",

                # ------------------------------------------------
                # RELIABILITY
                # ------------------------------------------------
                #
                # Idempotence protects against duplicate writes
                # caused by producer retries during transient
                # delivery failures.
                #
                # Note that business-level duplicate events are
                # still deliberately generated by our simulator
                # and must later be removed by Spark.
                # ------------------------------------------------

                "enable.idempotence": True,

                "acks": "all",

                "retries": 10,

                # ------------------------------------------------
                # PERFORMANCE
                # ------------------------------------------------

                "linger.ms": 10,

                "batch.num.messages": 10_000,

                "compression.type": "lz4",

                # ------------------------------------------------
                # PARTITIONING
                # ------------------------------------------------
                #
                # Murmur2 is compatible with Kafka's Java client
                # partitioning behaviour for keyed messages.
                # ------------------------------------------------

                "partitioner": "murmur2_random",
            }
        )

    # ========================================================
    # DELIVERY CALLBACK
    # ========================================================

    def _delivery_callback(
        self,
        error: Any,
        message: Any,
    ) -> None:
        """
        Called asynchronously by librdkafka when Kafka confirms
        whether a message was successfully delivered.
        """

        if error is not None:

            self.metrics.delivery_failures += 1

            print(
                "DELIVERY ERROR: "
                f"{error}"
            )

            return

        self.metrics.delivery_successes += 1

    # ========================================================
    # METRIC COLLECTION
    # ========================================================

    def _record_simulation_metrics(
        self,
        event: GeneratedTransaction,
    ) -> None:

        self.metrics.generated += 1

        if event.is_fraud_simulated:

            self.metrics.simulated_fraud += 1

            if event.fraud_type:

                self.fraud_type_counts[
                    event.fraud_type
                ] += 1

        if event.is_duplicate:

            self.metrics.duplicates += 1

        if (
            30
            <= event.lateness_seconds
            <= 5 * 60
        ):

            self.metrics.late_within_watermark += 1

        if event.lateness_seconds > 5 * 60:

            self.metrics.late_beyond_watermark += 1

    # ========================================================
    # SEND EVENT
    # ========================================================

    def send(
        self,
        event: GeneratedTransaction,
    ) -> None:
        """
        Serialize and asynchronously send one transaction.

        Only event.to_payload() is sent.

        Simulator-only fields such as:
            is_fraud_simulated
            fraud_type
            is_duplicate

        are intentionally excluded from Kafka.
        """

        payload = event.to_payload()

        serialized_payload = json.dumps(
            payload,
            separators=(",", ":"),
        ).encode(
            "utf-8"
        )

        key = event.user_id.encode(
            "utf-8"
        )

        while True:

            try:

                self.producer.produce(
                    topic=self.topic,

                    # ------------------------------------------
                    # USER ID IS THE PARTITIONING KEY
                    # ------------------------------------------

                    key=key,

                    value=serialized_payload,

                    headers={
                        "schema_version": "1.0",
                        "event_type": "financial_transaction",
                        "source": "synthetic_fraud_simulator",
                    },

                    on_delivery=(
                        self._delivery_callback
                    ),
                )

                break

            except BufferError:

                # The local producer queue is temporarily full.
                #
                # Polling allows completed deliveries to be
                # acknowledged and frees queue capacity rather
                # than allowing memory to grow without bound.

                self.producer.poll(
                    0.1
                )

        self._record_simulation_metrics(
            event
        )

        # Trigger asynchronous delivery callbacks without
        # blocking on every transaction.
        self.producer.poll(
            0
        )

    # ========================================================
    # SHUTDOWN
    # ========================================================

    def close(
        self,
        timeout_seconds: float = 30.0,
    ) -> int:
        """
        Flush outstanding messages before shutdown.

        Returns the number of undelivered messages remaining
        after the timeout.
        """

        return self.producer.flush(
            timeout_seconds
        )


# ============================================================
# CONSOLE REPORTING
# ============================================================

def print_periodic_metrics(
    *,
    kafka_producer: FraudKafkaProducer,
    elapsed_seconds: float,
) -> None:

    metrics = kafka_producer.metrics

    rate = (
        metrics.generated
        / elapsed_seconds
        if elapsed_seconds > 0
        else 0.0
    )

    print(
        "STREAMING | "
        f"generated={metrics.generated:,} | "
        f"delivered={metrics.delivery_successes:,} | "
        f"failed={metrics.delivery_failures:,} | "
        f"fraud={metrics.simulated_fraud:,} | "
        f"duplicates={metrics.duplicates:,} | "
        f"rate={rate:,.1f} events/sec"
    )


def print_final_summary(
    *,
    kafka_producer: FraudKafkaProducer,
    elapsed_seconds: float,
    undelivered_messages: int,
) -> None:

    metrics = kafka_producer.metrics

    average_rate = (
        metrics.generated
        / elapsed_seconds
        if elapsed_seconds > 0
        else 0.0
    )

    print()
    print("=" * 78)
    print(
        "KAFKA TRANSACTION PRODUCER SUMMARY"
    )
    print("=" * 78)

    print(
        f"Generated:                    "
        f"{metrics.generated:,}"
    )

    print(
        f"Kafka deliveries confirmed:  "
        f"{metrics.delivery_successes:,}"
    )

    print(
        f"Kafka delivery failures:      "
        f"{metrics.delivery_failures:,}"
    )

    print(
        f"Undelivered at shutdown:      "
        f"{undelivered_messages:,}"
    )

    print(
        f"Simulated fraud events:       "
        f"{metrics.simulated_fraud:,}"
    )

    print(
        f"Simulator duplicates:         "
        f"{metrics.duplicates:,}"
    )

    print(
        f"Late within 5 minutes:        "
        f"{metrics.late_within_watermark:,}"
    )

    print(
        f"Beyond 5 minutes:             "
        f"{metrics.late_beyond_watermark:,}"
    )

    print(
        f"Average generation rate:      "
        f"{average_rate:,.2f} events/sec"
    )

    if kafka_producer.fraud_type_counts:

        print()
        print(
            "Fraud scenarios:"
        )

        for (
            fraud_type,
            count,
        ) in sorted(
            kafka_producer
            .fraud_type_counts
            .items()
        ):

            print(
                f"  {fraud_type:<28} "
                f"{count:>8,}"
            )

    print("=" * 78)


# ============================================================
# STREAMING LOOP
# ============================================================

def run_producer(
    *,
    events_per_second: float,
    duration_seconds: float | None,
    maximum_events: int | None,
    number_of_users: int,
    fraud_rate: float,
    seed: int,
) -> None:

    bootstrap_servers = os.getenv(
        "KAFKA_BOOTSTRAP_SERVERS",
        "localhost:9092",
    )

    topic = os.getenv(
        "KAFKA_TRANSACTION_TOPIC",
        "transactions",
    )

    generator = TransactionGenerator(
        number_of_users=number_of_users,
        fraud_rate=fraud_rate,
        seed=seed,
    )

    kafka_producer = FraudKafkaProducer(
        bootstrap_servers=bootstrap_servers,
        topic=topic,
    )

    print("=" * 78)
    print(
        "REAL-TIME FRAUD DETECTION"
    )
    print(
        "LIVE KAFKA TRANSACTION PRODUCER"
    )
    print("=" * 78)

    print(
        f"Kafka:            "
        f"{bootstrap_servers}"
    )

    print(
        f"Topic:            "
        f"{topic}"
    )

    print(
        f"Users:            "
        f"{number_of_users:,}"
    )

    print(
        f"Target rate:      "
        f"{events_per_second:,.1f} events/sec"
    )

    print(
        f"Fraud rate:       "
        f"{fraud_rate:.2%}"
    )

    print()

    started_at = (
        time.perf_counter()
    )

    last_report_at = (
        started_at
    )

    target_interval = (
        1.0 / events_per_second
    )

    next_event_at = (
        started_at
    )

    try:

        while True:

            now = (
                time.perf_counter()
            )

            elapsed = (
                now - started_at
            )

            # ----------------------------------------------
            # OPTIONAL TERMINATION CONDITIONS
            # ----------------------------------------------

            if (
                duration_seconds is not None
                and elapsed >= duration_seconds
            ):

                break

            if (
                maximum_events is not None
                and kafka_producer.metrics.generated
                >= maximum_events
            ):

                break

            # ----------------------------------------------
            # RATE CONTROL
            # ----------------------------------------------

            if now < next_event_at:

                time.sleep(
                    min(
                        next_event_at - now,
                        0.01,
                    )
                )

                continue

            event = (
                generator.generate_event()
            )

            kafka_producer.send(
                event
            )

            next_event_at += (
                target_interval
            )

            # ----------------------------------------------
            # METRICS EVERY ~5 SECONDS
            # ----------------------------------------------

            now = (
                time.perf_counter()
            )

            if (
                now - last_report_at
                >= 5.0
            ):

                print_periodic_metrics(
                    kafka_producer=(
                        kafka_producer
                    ),
                    elapsed_seconds=(
                        now - started_at
                    ),
                )

                last_report_at = now

    except KeyboardInterrupt:

        print()
        print(
            "Shutdown requested."
        )

    finally:

        elapsed = (
            time.perf_counter()
            - started_at
        )

        print()
        print(
            "Flushing outstanding Kafka messages..."
        )

        undelivered = (
            kafka_producer.close()
        )

        print_final_summary(
            kafka_producer=kafka_producer,
            elapsed_seconds=elapsed,
            undelivered_messages=(
                undelivered
            ),
        )


# ============================================================
# CLI
# ============================================================

def parse_arguments() -> argparse.Namespace:

    parser = argparse.ArgumentParser(
        description=(
            "Continuously generate synthetic financial "
            "transactions and publish them to Kafka."
        )
    )

    parser.add_argument(
        "--rate",
        type=float,
        default=25.0,
        help=(
            "Target transactions per second."
        ),
    )

    parser.add_argument(
        "--duration",
        type=float,
        default=None,
        help=(
            "Optional run duration in seconds. "
            "Without this option the producer runs "
            "until Ctrl+C."
        ),
    )

    parser.add_argument(
        "--max-events",
        type=int,
        default=None,
        help=(
            "Optional maximum number of transactions."
        ),
    )

    parser.add_argument(
        "--users",
        type=int,
        default=2_000,
        help=(
            "Number of simulated user profiles."
        ),
    )

    parser.add_argument(
        "--fraud-rate",
        type=float,
        default=0.02,
        help=(
            "Probability of generating a fraud scenario."
        ),
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help=(
            "Random seed for reproducible simulations."
        ),
    )

    arguments = (
        parser.parse_args()
    )

    if arguments.rate <= 0:

        parser.error(
            "--rate must be greater than zero."
        )

    if (
        arguments.duration is not None
        and arguments.duration <= 0
    ):

        parser.error(
            "--duration must be greater than zero."
        )

    if (
        arguments.max_events is not None
        and arguments.max_events <= 0
    ):

        parser.error(
            "--max-events must be greater than zero."
        )

    return arguments


def main() -> None:

    arguments = (
        parse_arguments()
    )

    try:

        run_producer(
            events_per_second=(
                arguments.rate
            ),
            duration_seconds=(
                arguments.duration
            ),
            maximum_events=(
                arguments.max_events
            ),
            number_of_users=(
                arguments.users
            ),
            fraud_rate=(
                arguments.fraud_rate
            ),
            seed=(
                arguments.seed
            ),
        )

    except KafkaException as error:

        raise SystemExit(
            f"Kafka producer failed: {error}"
        ) from error


if __name__ == "__main__":
    main()